# Generated by Django 5.1.15 on 2026-07-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0012_alter_transferreceiptexception_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rows', models.JSONField(default=list, help_text='KDPS PT rows, keyed by the KDPS column names. Never hand-edited.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_pts_generated', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt', to='outbound.storetransfer')),
            ],
            options={
                'db_table': 'outbound_transfer_pt',
                'ordering': ['-generated_at'],
            },
        ),
    ]
