// What the counter's service worker is allowed to keep (#189).
//
// A service worker is a proxy in front of every request the app makes, installed
// on a shop-floor machine and updated only when it feels like it. The one thing
// it must never do here is answer for `/api`: the till's offline copy is
// IndexedDB, it is the thing the money reasons about, and a second cached copy
// of the same facts is not redundancy - it is a disagreement that a store person
// has no way of seeing, let alone clearing.
//
// So these are assertions about the config rather than about behaviour, and that
// is the honest seam: the worker itself is generated by workbox at build time,
// and what we can hold in a unit test is the instruction we gave it.

import { describe, expect, it } from "vitest";

import { API_PREFIX, MANIFEST, PWA_OPTIONS } from "./config";

describe("the counter's service worker", () => {
  it("caches nothing at runtime", () => {
    // The whole rule in one assertion. Any entry here would be a second copy of
    // something the till already holds - or worse, of something it deliberately
    // does not, like a price the server has since changed.
    expect(PWA_OPTIONS.workbox?.runtimeCaching).toEqual([]);
  });

  it("precaches the shell by extension, and nothing that could be an API answer", () => {
    const globs = PWA_OPTIONS.workbox?.globPatterns ?? [];

    expect(globs.length).toBeGreaterThan(0);
    for (const glob of globs) {
      expect(glob, "a precache glob must name file types, not a path").toMatch(/\{[a-z0-9,]+\}$/);
      expect(glob).not.toContain(API_PREFIX);
      expect(glob, "JSON is what an API answers in").not.toMatch(/json/);
    }
  });

  it("never answers an API request with the app shell", () => {
    // The subtler half. Every in-app URL falls back to index.html, and without
    // this denylist a navigation-shaped request to /api would be answered with
    // HTML - which the caller would then try to parse as JSON, offline, with a
    // customer waiting.
    const denied = PWA_OPTIONS.workbox?.navigateFallbackDenylist ?? [];

    expect(PWA_OPTIONS.workbox?.navigateFallback).toBe("/index.html");
    expect(denied.some((pattern) => pattern.test("/api/sell/dataset"))).toBe(true);
    expect(denied.some((pattern) => pattern.test("/api/sell/sales"))).toBe(true);
    // And it must not swallow the app's own routes on the way past.
    expect(denied.some((pattern) => pattern.test("/sell"))).toBe(false);
    expect(denied.some((pattern) => pattern.test("/sell/till"))).toBe(false);
  });

  it("is installable, and constrains nobody it was not built for", () => {
    expect(PWA_OPTIONS.manifest).toBe(MANIFEST);
    expect(MANIFEST.name).toContain("KDPS");
    expect(MANIFEST.display).toBe("standalone");
    // One manifest serves the whole product - a warehouse person installs the
    // same app - so it opens the front door and lets the server's own
    // `landing_page` decide, rather than starting everybody at a counter.
    expect(MANIFEST.start_url).toBe("/");
    expect(MANIFEST.orientation, "a counter's shape is not a manager's").toBeUndefined();
    // Chrome will not offer to install without a 192 and a 512.
    const sizes = (MANIFEST.icons ?? []).map((icon) => icon.sizes);
    expect(sizes).toContain("192x192");
    expect(sizes).toContain("512x512");
  });

  it("precaches a bundle the size this app actually is", () => {
    // Workbox's default limit is 2 MB and it drops anything larger *silently*,
    // which leaves an app that installs, claims to work offline, and opens to
    // nothing.
    expect(PWA_OPTIONS.workbox?.maximumFileSizeToCacheInBytes ?? 0).toBeGreaterThan(2 * 1024 * 1024);
  });

  it("stays out of the way in development", () => {
    // A worker in front of HMR serves yesterday's module graph.
    expect(PWA_OPTIONS.devOptions?.enabled).toBe(false);
  });
});
