// The manager's PIN, checked offline (#182).
//
// The hashes below are **real Django output**, generated by this project's own
// `accounts.till_pin.hash_till_pin` against a fixed salt. That is the point of
// them: they are the golden vector that makes "the counter and the server agree
// about this credential" a tested property rather than two implementations of
// the same RFC that have never met. Regenerate with:
//
//   uv run python -c "import django,os; os.environ.setdefault('DJANGO_SETTINGS_MODULE','config.settings'); \
//     django.setup(); from django.contrib.auth.hashers import PBKDF2PasswordHasher; \
//     print(PBKDF2PasswordHasher().encode('4813','kdpsgolden0182salt'))"

import { describe, expect, it } from "vitest";

import { covers, verifyPin, whoAuthorised } from "./pin";
import type { TillManager } from "./types";

/** `4813`, hashed by Django. */
const KUMAR: TillManager = {
  user_id: 7,
  name: "R. Kumar",
  till_pin_hash:
    "pbkdf2_sha256$870000$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dgsJ5+cYkcYVb1xq49iBN1g=",
};

/** `190277`, hashed by Django - a six-digit PIN, and a second person. */
const SINHA: TillManager = {
  user_id: 9,
  name: "P. Sinha",
  till_pin_hash:
    "pbkdf2_sha256$870000$kdpsgolden0182salt$HR3V5JFuVpbDVei4HSJWa+xH7d9T6zwomsZzGPbaGt8=",
};

function withHash(hash: string): TillManager {
  return { ...KUMAR, till_pin_hash: hash };
}

describe("verifying a PIN against what the server hashed", () => {
  it("accepts the manager's own PIN", async () => {
    expect(await verifyPin(KUMAR, "4813")).toBe(true);
    expect(await verifyPin(SINHA, "190277")).toBe(true);
  });

  it("refuses another manager's PIN", async () => {
    expect(await verifyPin(KUMAR, "190277")).toBe(false);
  });

  it("refuses a wrong PIN, an empty one and a near miss", async () => {
    expect(await verifyPin(KUMAR, "4812")).toBe(false);
    expect(await verifyPin(KUMAR, "")).toBe(false);
    expect(await verifyPin(KUMAR, "48130")).toBe(false);
    expect(await verifyPin(KUMAR, " 4813")).toBe(false);
  });
});

describe("a hash the counter cannot read", () => {
  // Every one of these is a no. The shape to avoid is "if the check cannot run,
  // let it through" - a cap anybody can lift by breaking the check.
  it.each([
    ["blank", ""],
    ["another algorithm", "bcrypt_sha256$$2b$12$abcdefghijklmnopqrstuv"],
    ["too few parts", "pbkdf2_sha256$870000$saltonly"],
    ["no iterations", "pbkdf2_sha256$$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dg=="],
    ["nonsense iterations", "pbkdf2_sha256$many$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dg=="],
    ["no digest", "pbkdf2_sha256$870000$kdpsgolden0182salt$"],
  ])("refuses %s", async (_name, hash) => {
    expect(await verifyPin(withHash(hash), "4813")).toBe(false);
  });
});

describe("who authorised it", () => {
  const managers = [KUMAR, SINHA];

  it("names the manager whose PIN it is, and what they authorised", async () => {
    const at = new Date("2026-07-31T09:15:00Z");

    const authorisation = await whoAuthorised(managers, "190277", ["over_cap_discount"], at);

    expect(authorisation).toEqual({
      user_id: 9,
      name: "P. Sinha",
      kinds: ["over_cap_discount"],
      at: "2026-07-31T09:15:00.000Z",
    });
  });

  it("answers nothing for a PIN belonging to nobody on this counter", async () => {
    expect(await whoAuthorised(managers, "0000", ["credit_note"])).toBeNull();
  });

  it("answers nothing when the counter knows no managers at all", async () => {
    // The seeded state today: no store role reaches the rung, so the list is
    // empty until an administrator grants it. An empty list authorises nothing.
    expect(await whoAuthorised([], "4813", ["credit_note"])).toBeNull();
  });
});

describe("what an authorisation covers", () => {
  const authorisation = {
    user_id: 7,
    name: "R. Kumar",
    kinds: ["credit_note"],
    at: "2026-07-31T09:15:00.000Z",
  };

  it("covers what the manager was shown", () => {
    expect(covers(authorisation, ["credit_note"])).toBe(true);
  });

  it("does not stretch to an exception keyed in after they walked away", () => {
    expect(covers(authorisation, ["credit_note", "over_cap_discount"])).toBe(false);
  });

  it("is not needed by a bill that needs nothing", () => {
    expect(covers(null, [])).toBe(true);
  });

  it("is needed by a bill that needs something", () => {
    expect(covers(null, ["over_cap_discount"])).toBe(false);
  });
});
