// The manager's PIN, checked offline (#182).
//
// The hashes below are **real Django output**, generated by this project's own
// `accounts.till_pin.hash_till_pin` against a fixed salt. That is the point of
// them: they are the golden vector that makes "the counter and the server agree
// about this credential" a tested property rather than two implementations of
// the same RFC that have never met. Regenerate with:
//
//   uv run python -c "import django,os; os.environ.setdefault('DJANGO_SETTINGS_MODULE','config.settings'); \
//     django.setup(); from django.contrib.auth.hashers import PBKDF2PasswordHasher; \
//     print(PBKDF2PasswordHasher().encode('4813','kdpsgolden0182salt'))"

import { describe, expect, it } from "vitest";

import {
  covers,
  kindsOf,
  LATE_RETURN,
  verifyPin,
  whoAuthorised,
} from "./pin";
import type { Ask } from "./pin";
import type { TillManager } from "./types";

/** `4813`, hashed by Django. */
const KUMAR: TillManager = {
  user_id: 7,
  name: "R. Kumar",
  till_pin_hash:
    "pbkdf2_sha256$870000$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dgsJ5+cYkcYVb1xq49iBN1g=",
};

/** `190277`, hashed by Django - a six-digit PIN, and a second person. */
const SINHA: TillManager = {
  user_id: 9,
  name: "P. Sinha",
  till_pin_hash:
    "pbkdf2_sha256$870000$kdpsgolden0182salt$HR3V5JFuVpbDVei4HSJWa+xH7d9T6zwomsZzGPbaGt8=",
};

function withHash(hash: string): TillManager {
  return { ...KUMAR, till_pin_hash: hash };
}

describe("verifying a PIN against what the server hashed", () => {
  it("accepts the manager's own PIN", async () => {
    expect(await verifyPin(KUMAR, "4813")).toBe(true);
    expect(await verifyPin(SINHA, "190277")).toBe(true);
  });

  it("refuses another manager's PIN", async () => {
    expect(await verifyPin(KUMAR, "190277")).toBe(false);
  });

  it("refuses a wrong PIN, an empty one and a near miss", async () => {
    expect(await verifyPin(KUMAR, "4812")).toBe(false);
    expect(await verifyPin(KUMAR, "")).toBe(false);
    expect(await verifyPin(KUMAR, "48130")).toBe(false);
    expect(await verifyPin(KUMAR, " 4813")).toBe(false);
  });
});

describe("a hash the counter cannot read", () => {
  // Every one of these is a no. The shape to avoid is "if the check cannot run,
  // let it through" - a cap anybody can lift by breaking the check.
  it.each([
    ["blank", ""],
    ["another algorithm", "bcrypt_sha256$$2b$12$abcdefghijklmnopqrstuv"],
    ["too few parts", "pbkdf2_sha256$870000$saltonly"],
    ["no iterations", "pbkdf2_sha256$$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dg=="],
    ["nonsense iterations", "pbkdf2_sha256$many$kdpsgolden0182salt$rialnJCXB+CGhwwjSRU/dg=="],
    ["no digest", "pbkdf2_sha256$870000$kdpsgolden0182salt$"],
  ])("refuses %s", async (_name, hash) => {
    expect(await verifyPin(withHash(hash), "4813")).toBe(false);
  });
});

/** A bill being returned after the configured window. */
function note(ref: string, paise: number): Ask {
  return { kind: LATE_RETURN, ref, paise, label: ref };
}

describe("who authorised it", () => {
  const managers = [KUMAR, SINHA];

  it("names the manager whose PIN it is, and exactly what they were shown", async () => {
    const at = new Date("2026-07-31T09:15:00Z");

    const attempt = await whoAuthorised(managers, "190277", [note("CRN/9", 20000)], at);

    expect(attempt.authorisation).toEqual({
      user_id: 9,
      name: "P. Sinha",
      asks: [note("CRN/9", 20000)],
      at: "2026-07-31T09:15:00.000Z",
    });
  });

  it("keeps its own copy of what was on the screen", async () => {
    // The cart goes on changing after the manager walks away. An authorisation
    // holding a reference into it would quietly agree to whatever it became.
    const asks = [note("CRN/9", 20000)];

    const attempt = await whoAuthorised(managers, "4813", asks);
    asks[0].paise = 2000000;

    expect(attempt.authorisation?.asks[0].paise).toBe(20000);
  });

  it("answers nothing for a PIN belonging to nobody on this counter", async () => {
    const attempt = await whoAuthorised(managers, "0000", [note("CRN/9", 50000)]);

    expect(attempt).toEqual({ authorisation: null, matched: 0 });
  });

  it("answers nothing when the counter knows no managers at all", async () => {
    // The seeded state today: no store role reaches the rung, so the list is
    // empty until an administrator grants it. An empty list authorises nothing.
    const attempt = await whoAuthorised([], "4813", [note("CRN/9", 50000)]);

    expect(attempt).toEqual({ authorisation: null, matched: 0 });
  });

  it("authorises nobody when two managers share a PIN, and says how many", async () => {
    // Four digits is a small space. "The first one that matches" would put one
    // manager's name on a bill the other one approved, with nothing afterwards
    // able to tell - so an ambiguous PIN is refused and said out loud.
    const twin = { ...SINHA, user_id: 11, name: "S. Das", till_pin_hash: KUMAR.till_pin_hash };

    const attempt = await whoAuthorised([KUMAR, twin], "4813", [note("CRN/9", 100)]);

    expect(attempt).toEqual({ authorisation: null, matched: 2 });
    expect((await whoAuthorised([KUMAR, twin], "190277", [])).matched).toBe(0);
  });
});

describe("what an authorisation covers", () => {
  const authorisation = {
    user_id: 7,
    name: "R. Kumar",
    asks: [note("26-27/XXX/CRN/9", 50000)],
    at: "2026-07-31T09:15:00.000Z",
  };

  it("covers exactly what the manager was shown", () => {
    expect(covers(authorisation, [note("26-27/XXX/CRN/9", 50000)])).toBe(true);
    expect(covers(authorisation, authorisation.asks)).toBe(true);
  });

  it("covers less than they agreed to", () => {
    expect(covers(authorisation, [note("26-27/XXX/CRN/9", 10000)])).toBe(true);
  });

  it("does not stretch to a larger amount on the same note", () => {
    expect(covers(authorisation, [note("26-27/XXX/CRN/9", 50001)])).toBe(false);
  });

  it("does not stretch to a second unknown note", () => {
    expect(covers(authorisation, [note("26-27/XXX/CRN/10", 100)])).toBe(false);
  });

  it("is not needed by a bill that asks for nothing", () => {
    expect(covers(null, [])).toBe(true);
  });

  it("is needed by a bill that asks for something", () => {
    expect(covers(null, [note("CRN/9", 1)])).toBe(false);
  });
});

describe("the kinds among a set of asks", () => {
  it("is always written in one order, whatever order they arrived in", () => {
    const asks = [note("CRN/9", 1), note("CRN/10", 1)];

    expect(kindsOf(asks)).toEqual(["late_return"]);
  });

  it("is empty for an ordinary bill", () => {
    expect(kindsOf([])).toEqual([]);
  });
});
