#!/usr/bin/env bash
# KDPS local dev stack — Postgres (Docker) + Django API + React PWA.
#
#   ./scripts/dev.sh              bring the whole stack up (Ctrl-C stops it)
#   ./scripts/dev.sh --setup-only provision DB + deps + seed, start no servers
#   ./scripts/dev.sh --reset      destroy this workspace's DB and rebuild it
#   ./scripts/dev.sh --down       stop this workspace's Postgres (data kept)
#   ./scripts/dev.sh --api        API only          --web   PWA only
#   ./scripts/dev.sh --seed       re-seed demo data  --no-seed  never seed
#   ./scripts/dev.sh --free-ports kill whatever holds this workspace's ports
#   ./scripts/dev.sh --where      print this workspace's project name and ports
#
# TWO JOBS, ONE SCRIPT, AND THEY NEVER FIGHT.
#   Provision (`--setup-only`, the Conductor setup hook): create this workspace's
#     Postgres container and volume, install deps, migrate, seed. Slow, once.
#   Serve (no flag, the Run button): start the API and the PWA. Fast, often.
# Serving still *checks* that the database is up and the schema current — a
# rebase can add migrations, and a Mac reboot stops the container — but it
# installs nothing that is already installed and re-seeds nothing already seeded.
#
# Both jobs take a per-workspace provisioning lock before touching Docker, deps
# or the schema, and the serve path waits on it rather than failing. Conductor
# runs setup when a workspace is created and Anand clicks Run seconds later, so
# the two DO overlap — and two concurrent `docker compose up` calls on one
# project is a hard error ("Conflict. The container name ... is already in use"),
# not a no-op. The lock is what makes clicking Run during setup simply wait.
#
# EVERY WORKSPACE IS ITS OWN SYSTEM. Container, volume, database and all three
# ports come from scripts/workspace-env.sh, keyed on the Conductor workspace, so
# two workspaces can run this at once and neither can migrate, seed or drop the
# other's data. Outside Conductor it falls back to the old fixed 3000/8001/55432.
#
# Idempotent: safe to re-run. Nothing here touches Render — see DEPLOY.md for that.
# Predecessors scripts/{dev-bootstrap,pg_run,app_init}.sh target the Emergent
# container (/root/.venv, apt, supervisor) and do not run on a dev machine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND="$ROOT/app/backend"
FRONTEND="$ROOT/app/frontend"
ENV_FILE="$BACKEND/.env"

# shellcheck source=scripts/workspace-env.sh
. "$ROOT/scripts/workspace-env.sh"

API_PORT="$KDPS_API_PORT"
WEB_PORT="$KDPS_WEB_PORT"
COMPOSE=(docker compose -p "$KDPS_PROJECT" -f "$ROOT/docker-compose.yml")

# SEED=auto: seed when provisioning, and when serving finds an empty database —
# but not on every Run click, which would re-import the master sheets for nothing.
RUN_API=1 RUN_WEB=1 SEED=auto RESET=0 SETUP_ONLY=0 FREE_PORTS=0 DOWN=0 WHERE=0
for arg in "$@"; do
  case "$arg" in
    --setup-only) SETUP_ONLY=1 ;;
    --reset)      RESET=1 ;;
    --down)       DOWN=1 ;;
    --where)      WHERE=1 ;;
    --api)        RUN_WEB=0 ;;
    --web)        RUN_API=0 ;;
    --seed)       SEED=1 ;;
    --no-seed)    SEED=0 ;;
    --free-ports) FREE_PORTS=1 ;;
    -h|--help)    sed -n '2,19p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m fail\033[0m %s\n' "$*" >&2; exit 1; }

if [ "$WHERE" = 1 ]; then
  printf 'workspace  %s\n'  "$KDPS_SLUG"
  printf 'compose    %s\n'  "$KDPS_PROJECT"
  printf 'PWA        http://localhost:%s\n' "$WEB_PORT"
  printf 'API        %s\n'  "$KDPS_BACKEND_URL"
  printf 'database   %s\n'  "$KDPS_DATABASE_URL"
  exit 0
fi

# --- 1. preflight ------------------------------------------------------------
say "Preflight · workspace '$KDPS_SLUG' → PWA :$WEB_PORT · API :$API_PORT · PG :$KDPS_PG_PORT"
for tool in docker uv node; do
  command -v "$tool" >/dev/null || die "$tool not found. Need Docker, uv and Node 22."
done
docker info >/dev/null 2>&1 || die "Docker is installed but not running — start Docker Desktop."

if [ "$DOWN" = 1 ]; then
  say "Stopping $KDPS_PROJECT (data volume kept — use --reset to wipe it)"
  "${COMPOSE[@]}" down
  exit 0
fi

# --- 2. env ------------------------------------------------------------------
# Generated, never committed (.gitignore:52). No Render values are used or needed:
# the only real secret (EMERGENT_LLM_KEY, the Gemini invoice reader) is inert
# here because `aiagents` is not in INSTALLED_APPS.
if [ ! -f "$ENV_FILE" ]; then
  say "Writing $ENV_FILE (first run)"
  secret="$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')"
  cat > "$ENV_FILE" <<EOF
# Local dev only. Generated by scripts/dev.sh — not the Render config.
DJANGO_SECRET_KEY=$secret
DJANGO_DEBUG=1
DJANGO_ALLOWED_HOSTS=*
SEED_DEMO=1
# DEBUG=1 already allows every http://localhost:<port> origin via
# CORS_ALLOWED_ORIGIN_REGEXES (settings.py:153), so the PWA reaches the API with
# no extra CORS config, whatever ports this workspace was given.
JWT_COOKIE_SECURE=0
GEMINI_MODEL=gemini-2.5-flash
EOF
else
  say "Using existing $ENV_FILE"
fi

# DATABASE_URL and REACT_APP_BACKEND_URL are rewritten on EVERY run, not written
# once. Conductor's Files-to-copy seeds each new workspace with a copy of the root
# checkout's `.env` (its default pattern is `.env*`), so a fresh workspace starts
# life holding some *other* workspace's port — pointing this stack at that
# workspace's database, quietly and with no error. These two keys belong to
# workspace-env.sh; everything else in the file is yours to edit.
env_set() {
  local file="$1" key="$2" value="$3" tmp
  tmp="$(mktemp)"
  [ -f "$file" ] && grep -v "^${key}=" "$file" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$file"
}
env_drop() {
  local file="$1" key="$2" tmp
  [ -f "$file" ] || return 0
  tmp="$(mktemp)"
  grep -v "^${key}=" "$file" > "$tmp" || true
  mv "$tmp" "$file"
}
env_set "$ENV_FILE"       DATABASE_URL          "$KDPS_DATABASE_URL"
env_set "$FRONTEND/.env"  REACT_APP_BACKEND_URL "$KDPS_BACKEND_URL"
# The frontend's API base belongs to the frontend's own .env, and only there.
# A copy of it in the *backend* .env is sourced below with `set -a`, so it
# reaches Vite as a process env var — which outranks the file we just wrote, and
# points the PWA at another workspace's port. Older workspaces carry exactly
# that stale key, so drop it rather than trust it.
env_drop "$ENV_FILE"      REACT_APP_BACKEND_URL

set -a; . "$ENV_FILE"; set +a
: "${DATABASE_URL:?DATABASE_URL missing from $ENV_FILE}"

# --- 3. refuse to touch a non-local database ---------------------------------
# This script runs migrate / seed / (via npm run ci) pytest's CREATE+DROP DATABASE.
# Those must never reach the Render alpha or any shared Postgres, so the host is
# whitelisted rather than trusted. A dev DB is disposable; a real one is not.
db_host="$(printf '%s' "$DATABASE_URL" | sed -E 's#^[^:]+://([^@]*@)?([^:/?]+).*#\2#')"
case "$db_host" in
  localhost|127.0.0.1|::1|"") ;;
  *) die "DATABASE_URL points at a remote host ('$db_host').
       This script only ever runs against a local database — it applies migrations,
       seeds demo data, and its sibling gate drops databases. Point DATABASE_URL at
       localhost, or use the Render dashboard for the alpha." ;;
esac

# --- 4. one provisioning at a time -------------------------------------------
# Everything from here to the end of section 7 mutates shared state that belongs
# to the workspace, not to this process: the Docker container, the virtualenv,
# node_modules, the schema. Conductor's setup hook and the Run button are two
# separate processes that routinely overlap, so this is a real race, not a
# theoretical one — and `docker compose up` loses it loudly:
#
#   Conflict. The container name "/kdps-<workspace>-db-1" is already in use
#
# A directory is the lock: mkdir is atomic on every filesystem we care about, and
# unlike `flock` it exists on macOS. The owner's PID goes inside so a lock left
# behind by a SIGKILLed run can be told apart from one that is genuinely held.
LOCK_DIR="${TMPDIR:-/tmp}/${KDPS_PROJECT}.provision.lock"
LOCK_HELD=0

release_lock() {
  if [ "$LOCK_HELD" = 1 ]; then
    LOCK_HELD=0
    rm -rf "$LOCK_DIR"
  fi
}

acquire_lock() {
  local waited=0 pid=''
  until mkdir "$LOCK_DIR" 2>/dev/null; do
    pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
    if [ -z "$pid" ]; then
      # The owner creates the directory and writes its PID a moment later, so an
      # empty lock is usually one being taken. Only call it abandoned after a few
      # seconds of nobody claiming it.
      if [ "$waited" -lt 5 ]; then
        sleep 1; waited=$((waited + 1)); continue
      fi
      warn "Clearing an unclaimed provisioning lock at $LOCK_DIR"
      rm -rf "$LOCK_DIR"; continue
    fi
    if ! kill -0 "$pid" 2>/dev/null; then
      warn "Clearing a stale provisioning lock — its owner (PID $pid) is gone"
      rm -rf "$LOCK_DIR"; continue
    fi
    if [ "$waited" = 0 ]; then
      say "This workspace is being provisioned by PID $pid (setup, probably) — waiting"
    fi
    sleep 1
    waited=$((waited + 1))
    if [ "$waited" -ge 900 ]; then
      die "Waited 15 minutes for PID $pid to finish provisioning this workspace.
       If it is wedged: kill $pid, then remove $LOCK_DIR."
    fi
  done
  printf '%s\n' "$$" > "$LOCK_DIR/pid"
  LOCK_HELD=1
  if [ "$waited" -gt 0 ]; then
    say "Provisioning finished after ${waited}s — carrying on"
  fi
}

# Released explicitly once provisioning is done (section 7), so the servers do
# not hold it for their whole life. This trap covers the `die` paths in between;
# cleanup() replaces it in section 9 and calls release_lock itself.
trap release_lock HUP INT TERM EXIT
acquire_lock

# --- 5. database -------------------------------------------------------------
if [ "$RESET" = 1 ]; then
  warn "--reset: destroying this workspace's Postgres volume ($KDPS_PROJECT). Other workspaces are untouched."
  "${COMPOSE[@]}" down -v
fi

say "Postgres (docker compose · $KDPS_PROJECT · localhost:$KDPS_PG_PORT)"
"${COMPOSE[@]}" up -d db >/dev/null

printf '    waiting for healthy'
for _ in $(seq 1 60); do
  if "${COMPOSE[@]}" exec -T db pg_isready -U kdps -d kdps_dev >/dev/null 2>&1; then
    printf ' ok\n'; break
  fi
  printf '.'; sleep 1
done
"${COMPOSE[@]}" exec -T db pg_isready -U kdps -d kdps_dev >/dev/null 2>&1 \
  || die "Postgres did not come up. Check: docker compose -p $KDPS_PROJECT logs db
       If host port $KDPS_PG_PORT is taken, something outside Conductor is holding it."

# An empty database has to be seeded whoever asked for it — a Run click on a
# workspace whose setup never ran, or died between migrating and seeding, must
# still end at an app you can log into. So the question is "are there users?",
# not "is there a schema": a migrated-but-unseeded database has every table and
# no way in, which is the more confusing of the two failures. Asked in SQL rather
# than through Django because it costs a query, not an interpreter start.
FRESH_DB=0
if ! "${COMPOSE[@]}" exec -T db psql -U kdps -d kdps_dev -tAc \
     "select count(*) from accounts_user" 2>/dev/null | grep -qE '[1-9]'; then
  FRESH_DB=1
fi

# --- 6. dependencies ---------------------------------------------------------
# Install when the lockfile has moved since the last install, and not otherwise.
# The stamp lives *inside* the tree it describes, so deleting .venv or
# node_modules invalidates it for free. This is stricter than "skip if the
# directory exists" — a branch switch that changes a lockfile reinstalls, which
# is the failure the old unconditional install was defending against — and it
# costs nothing on the common path, where the lockfile has not moved.
sha_of() {
  if command -v shasum >/dev/null; then shasum -a 256 "$1" | cut -d' ' -f1
  else sha256sum "$1" | cut -d' ' -f1; fi
}
deps_current() {   # deps_current <lockfile> <stamp>  → 0 when the install is up to date
  local lock="$1" stamp="$2"
  [ -f "$lock" ] || return 1
  [ -f "$stamp" ] || return 1
  [ "$(sha_of "$lock")" = "$(cat "$stamp")" ]
}

UV_STAMP="$BACKEND/.venv/.kdps-deps-sha"
YARN_STAMP="$FRONTEND/node_modules/.kdps-deps-sha"

if deps_current "$BACKEND/uv.lock" "$UV_STAMP"; then
  say "Dependencies · backend up to date"
else
  say "Dependencies · backend (uv sync)"
  (cd "$BACKEND" && uv sync --quiet)
  sha_of "$BACKEND/uv.lock" > "$UV_STAMP"
fi

# The frontend is a YARN project: yarn.lock is the committed lockfile and cloud CI
# runs `yarn install --frozen-lockfile` (.github/workflows/ci.yml:107). Do not run
# `npm install` here — npm 7+ rewrites an existing yarn.lock in place (rewriting
# every `resolved` URL and pruning entries), which then fails CI's --frozen-lockfile.
# Install the same way CI does, so local and cloud resolve identical trees.
if [ -f "$FRONTEND/yarn.lock" ]; then
  command -v yarn >/dev/null || die "yarn not found, but app/frontend/yarn.lock exists (CI uses yarn). Install it: npm i -g yarn"
  if deps_current "$FRONTEND/yarn.lock" "$YARN_STAMP"; then
    say "Dependencies · frontend up to date"
  else
    say "Dependencies · frontend (yarn install)"
    (cd "$FRONTEND" && yarn install --frozen-lockfile --silent)
    sha_of "$FRONTEND/yarn.lock" > "$YARN_STAMP"
  fi
else
  (cd "$FRONTEND" && npm install --silent --no-audit --no-fund)
fi

# --- 7. schema + seed --------------------------------------------------------
say "Migrations"
# This database belongs to this workspace alone, so leftover schema can only be
# your own, from an earlier branch of this same worktree. Still possible, still
# fixed the same way — and we never auto-reset, because that destroys data and
# the choice stays yours.
if ! (cd "$BACKEND" && uv run python manage.py migrate --noinput); then
  die "Migrations failed. If this workspace's database carries leftover schema from
       an earlier branch of this worktree ('relation ... already exists'), rebuild it:
         ./scripts/dev.sh --reset"
fi

# Seeding is idempotent but not free — it re-reads the master sheets. Provisioning
# always does it; serving only does it for a database that has nothing in it yet.
# `--seed` forces it, `--no-seed` forbids it.
if [ "$SEED" = auto ]; then
  if [ "$SETUP_ONLY" = 1 ] || [ "$FRESH_DB" = 1 ]; then SEED=1; else SEED=0; fi
fi
if [ "$SEED" = 1 ] && [ "$SETUP_ONLY" = 0 ] && [ "$FRESH_DB" = 1 ]; then
  warn "This workspace's database was empty — seeding it now. Normally 'npm run dev:setup' has already done this."
fi

if [ "$SEED" = 1 ]; then
  say "Seed (idempotent)"
  # All three are re-runnable. The last two are tolerated failing so a seed-data
  # bug never blocks booting the app. Same set, same order as cloud CI
  # (.github/workflows/ci.yml) - the live-API suites are written against exactly
  # this fixture data, and seed_outbound_demo is the on-hand stock the RTV suites
  # spend, so leaving it out makes them skip after every --reset (issue #93).
  (cd "$BACKEND" && uv run python manage.py seed_foundation)
  (cd "$BACKEND" && uv run python manage.py seed_ptmapper) || warn "seed_ptmapper failed — PT-mapper lookups may be empty"
  (cd "$BACKEND" && uv run python manage.py seed_outbound_demo) || warn "seed_outbound_demo failed - outbound/RTV suites will skip for want of stock"
fi

# Provisioning ends here, so the lock ends here. Holding it across the servers'
# whole lifetime would block the next `--setup-only` for as long as the app runs.
release_lock

if [ "$SETUP_ONLY" = 1 ]; then
  say "Setup complete. Press Run (or ./scripts/dev.sh) to start the servers."
  exit 0
fi

# --- 8. ports ----------------------------------------------------------------
# These ports belong to this workspace, so a holder is most likely this
# workspace's own orphan from a run that was SIGKILLed. Most likely is not
# certainly, and killing another project's server would be unforgivable, so we
# report and stop unless explicitly told otherwise.
for port_pair in "$API_PORT:API" "$WEB_PORT:PWA"; do
  port="${port_pair%%:*}"; label="${port_pair##*:}"
  [ "$label" = API ] && [ "$RUN_API" = 0 ] && continue
  [ "$label" = PWA ] && [ "$RUN_WEB" = 0 ] && continue
  # `|| true`: lsof exits non-zero when the port is free, which would trip
  # `set -e`/pipefail - an empty result is the normal, expected case here.
  holder="$(lsof -ti:"$port" 2>/dev/null | tr '\n' ' ' || true)"
  holder="$(printf '%s' "$holder" | xargs)"   # trim to a clean space-joined PID list
  [ -n "$holder" ] || continue
  what="$(ps -o command= -p $holder 2>/dev/null | head -1)"
  if [ "$FREE_PORTS" = 1 ]; then
    warn "Port ${port} (${label}) held by PID ${holder} - freeing (--free-ports): ${what}"
    kill $holder 2>/dev/null || true
    for _ in $(seq 1 10); do lsof -ti:"$port" >/dev/null 2>&1 || break; sleep 0.5; done
    lsof -ti:"$port" >/dev/null 2>&1 && die "Port ${port} still in use after kill - free it manually."
  else
    die "Port ${port} (${label}) is already in use by PID ${holder} (${what}).
       This workspace owns that port, so it is probably its own leftover server.
       Reclaim it and start: ./scripts/dev.sh --free-ports
       Or free it yourself: kill \$(lsof -ti:${port})"
  fi
done

# --- 9. run ------------------------------------------------------------------
pids=()
cleanup() {
  trap - HUP INT TERM EXIT
  release_lock   # a no-op unless we died before section 7 released it
  [ ${#pids[@]} -gt 0 ] && kill "${pids[@]}" 2>/dev/null || true
  wait 2>/dev/null || true
  say "Stopped. Postgres is still up — './scripts/dev.sh --down' stops it too."
}
# HUP as well as INT/TERM: Conductor's Run button stops a script with SIGHUP and
# SIGKILLs it 200ms later, so an untrapped HUP would leave both servers orphaned
# on this workspace's ports.
trap cleanup HUP INT TERM EXIT

if [ "$RUN_API" = 1 ]; then
  say "API   → $KDPS_BACKEND_URL  (admin: /admin, health: /api/finledger/health)"
  (cd "$BACKEND" && exec uv run python manage.py runserver "$API_PORT") & pids+=($!)
fi
if [ "$RUN_WEB" = 1 ]; then
  say "PWA   → http://localhost:$WEB_PORT"
  # VITE_LOCAL_DEV drops the Emergent HTTPS-proxy HMR port (vite.config.ts), which
  # would otherwise make the browser dial wss://localhost:443 and break hot reload.
  # --port overrides vite.config.ts's strictPort 3000 for this workspace.
  (cd "$FRONTEND" && VITE_LOCAL_DEV=1 exec npm run dev -- --port "$WEB_PORT") & pids+=($!)
fi

say "Logins: see memory/test_credentials.md (e.g. owner / Owner@123). Ctrl-C to stop."
wait
