#!/usr/bin/env bash
# KDPS local dev stack — Postgres (Docker) + Django API + React PWA.
#
#   ./scripts/dev.sh              bring the whole stack up (Ctrl-C stops it)
#   ./scripts/dev.sh --setup-only provision DB + deps + seed, start no servers
#   ./scripts/dev.sh --reset      destroy the local DB and rebuild it from scratch
#   ./scripts/dev.sh --api        API only          --web   PWA only
#   ./scripts/dev.sh --no-seed    skip seeding (migrations still run)
#
# Idempotent: safe to re-run. Nothing here touches Render — see DEPLOY.md for that.
# Predecessors scripts/{dev-bootstrap,pg_run,app_init}.sh target the Emergent
# container (/root/.venv, apt, supervisor) and do not run on a dev machine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND="$ROOT/app/backend"
FRONTEND="$ROOT/app/frontend"
ENV_FILE="$BACKEND/.env"

API_PORT=8001   # app/frontend/.env pins REACT_APP_BACKEND_URL to this
WEB_PORT=3000   # vite.config.ts sets strictPort — 3000 or nothing

RUN_API=1 RUN_WEB=1 SEED=1 RESET=0 SETUP_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --setup-only) SETUP_ONLY=1 ;;
    --reset)      RESET=1 ;;
    --api)        RUN_WEB=0 ;;
    --web)        RUN_API=0 ;;
    --no-seed)    SEED=0 ;;
    -h|--help)    sed -n '2,10p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m fail\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. preflight ------------------------------------------------------------
say "Preflight"
for tool in docker uv node; do
  command -v "$tool" >/dev/null || die "$tool not found. Need Docker, uv and Node 22."
done
docker info >/dev/null 2>&1 || die "Docker is installed but not running — start Docker Desktop."

# --- 2. env ------------------------------------------------------------------
# Generated, never committed (.gitignore:52). No Render values are used or needed:
# the only real secret (EMERGENT_LLM_KEY, the Gemini invoice reader) is inert
# here because `aiagents` is not in INSTALLED_APPS.
if [ ! -f "$ENV_FILE" ]; then
  say "Writing $ENV_FILE (first run)"
  secret="$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')"
  cat > "$ENV_FILE" <<EOF
# Local dev only. Generated by scripts/dev.sh — not the Render config.
DATABASE_URL=postgres://kdps:kdps@localhost:55432/kdps_dev
DJANGO_SECRET_KEY=$secret
DJANGO_DEBUG=1
DJANGO_ALLOWED_HOSTS=*
SEED_DEMO=1
# DEBUG=1 already allows every http://localhost:<port> origin via
# CORS_ALLOWED_ORIGIN_REGEXES (settings.py:153), so the PWA on :$WEB_PORT
# reaches the API on :$API_PORT with no extra CORS config.
JWT_COOKIE_SECURE=0
GEMINI_MODEL=gemini-2.5-flash
EOF
else
  say "Using existing $ENV_FILE"
fi

set -a; . "$ENV_FILE"; set +a
: "${DATABASE_URL:?DATABASE_URL missing from $ENV_FILE}"

[ -f "$FRONTEND/.env" ] || echo "REACT_APP_BACKEND_URL=http://localhost:$API_PORT" > "$FRONTEND/.env"

# --- 3. refuse to touch a non-local database ---------------------------------
# This script runs migrate / seed / (via npm run ci) pytest's CREATE+DROP DATABASE.
# Those must never reach the Render alpha or any shared Postgres, so the host is
# whitelisted rather than trusted. A dev DB is disposable; a real one is not.
db_host="$(printf '%s' "$DATABASE_URL" | sed -E 's#^[^:]+://([^@]*@)?([^:/?]+).*#\2#')"
case "$db_host" in
  localhost|127.0.0.1|::1|"") ;;
  *) die "DATABASE_URL points at a remote host ('$db_host').
       This script only ever runs against a local database — it applies migrations,
       seeds demo data, and its sibling gate drops databases. Point DATABASE_URL at
       localhost, or use the Render dashboard for the alpha." ;;
esac

# --- 4. database -------------------------------------------------------------
if [ "$RESET" = 1 ]; then
  warn "--reset: destroying the local Postgres volume"
  docker compose -f "$ROOT/docker-compose.yml" down -v
fi

say "Postgres (docker compose · localhost:55432)"
docker compose -f "$ROOT/docker-compose.yml" up -d db >/dev/null

printf '    waiting for healthy'
for _ in $(seq 1 60); do
  if docker compose -f "$ROOT/docker-compose.yml" exec -T db pg_isready -U kdps -d kdps_dev >/dev/null 2>&1; then
    printf ' ok\n'; break
  fi
  printf '.'; sleep 1
done
docker compose -f "$ROOT/docker-compose.yml" exec -T db pg_isready -U kdps -d kdps_dev >/dev/null 2>&1 \
  || die "Postgres did not come up. Check: docker compose logs db"

# --- 5. dependencies ---------------------------------------------------------
say "Dependencies"
(cd "$BACKEND" && uv sync --quiet)
# The frontend is a YARN project: yarn.lock is the committed lockfile and cloud CI
# runs `yarn install --frozen-lockfile` (.github/workflows/ci.yml:107). Do not run
# `npm install` here — npm 7+ rewrites an existing yarn.lock in place (rewriting
# every `resolved` URL and pruning entries), which then fails CI's --frozen-lockfile.
# Install the same way CI does, so local and cloud resolve identical trees.
#
# Always install, never "skip if node_modules exists" — a present-but-stale
# node_modules survives branch switches and leaves packages missing with no visible
# error until tsc or vitest fails. yarn is a fast no-op when already satisfied.
if [ -f "$FRONTEND/yarn.lock" ]; then
  command -v yarn >/dev/null || die "yarn not found, but app/frontend/yarn.lock exists (CI uses yarn). Install it: npm i -g yarn"
  (cd "$FRONTEND" && yarn install --frozen-lockfile --silent)
else
  (cd "$FRONTEND" && npm install --silent --no-audit --no-fund)
fi

# --- 6. schema + seed --------------------------------------------------------
say "Migrations"
(cd "$BACKEND" && uv run python manage.py migrate --noinput)

if [ "$SEED" = 1 ]; then
  say "Seed (idempotent)"
  # Both are re-runnable; ptmapper seed is tolerated failing so a seed-data bug
  # never blocks booting the app.
  (cd "$BACKEND" && uv run python manage.py seed_foundation)
  (cd "$BACKEND" && uv run python manage.py seed_ptmapper) || warn "seed_ptmapper failed — PT-mapper lookups may be empty"
fi

if [ "$SETUP_ONLY" = 1 ]; then
  say "Setup complete. Run ./scripts/dev.sh to start the servers."
  exit 0
fi

# --- 7. ports ----------------------------------------------------------------
# A stale uvicorn from another checkout answering on :8001 silently poisons
# local testing — the PWA and the live-API tests would hit the wrong backend.
for port_pair in "$API_PORT:API" "$WEB_PORT:PWA"; do
  port="${port_pair%%:*}"; label="${port_pair##*:}"
  [ "$label" = API ] && [ "$RUN_API" = 0 ] && continue
  [ "$label" = PWA ] && [ "$RUN_WEB" = 0 ] && continue
  if lsof -ti:"$port" >/dev/null 2>&1; then
    die "Port $port ($label) is already in use by PID $(lsof -ti:"$port" | tr '\n' ' ').
       Likely a server from another checkout. Free it with: kill \$(lsof -ti:$port)"
  fi
done

# --- 8. run ------------------------------------------------------------------
pids=()
cleanup() {
  trap - INT TERM EXIT
  [ ${#pids[@]} -gt 0 ] && kill "${pids[@]}" 2>/dev/null || true
  wait 2>/dev/null || true
  say "Stopped. Postgres is still up — 'docker compose down' to stop it too."
}
trap cleanup INT TERM EXIT

if [ "$RUN_API" = 1 ]; then
  say "API   → http://localhost:$API_PORT  (admin: /admin, health: /api/finledger/health)"
  (cd "$BACKEND" && exec uv run python manage.py runserver "$API_PORT") & pids+=($!)
fi
if [ "$RUN_WEB" = 1 ]; then
  say "PWA   → http://localhost:$WEB_PORT"
  # VITE_LOCAL_DEV drops the Emergent HTTPS-proxy HMR port (vite.config.ts), which
  # would otherwise make the browser dial wss://localhost:443 and break hot reload.
  (cd "$FRONTEND" && VITE_LOCAL_DEV=1 exec npm run dev) & pids+=($!)
fi

say "Logins: see memory/test_credentials.md (e.g. owner / Owner@123). Ctrl-C to stop."
wait
