/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/admin/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_admin_meta_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_admin_roles_list"];
        put?: never;
        post: operations["auth_admin_roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_admin_roles_retrieve"];
        put: operations["auth_admin_roles_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_admin_roles_partial_update"];
        trace?: never;
    };
    "/api/auth/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_admin_users_list"];
        put?: never;
        post: operations["auth_admin_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_admin_users_retrieve"];
        put: operations["auth_admin_users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_admin_users_partial_update"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bookings_list"];
        put?: never;
        post: operations["bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bookings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Read an uploaded receiving doc into a draft booking (not saved). */
        post: operations["bookings_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["files_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/cash/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finledger_cash_entries_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/cash/entries/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finledger_cash_entries_reverse_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/cash/movement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finledger_cash_movement_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/cash/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finledger_cash_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/ageing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finledger_vendor_ageing_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finledger_vendor_balances_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finledger_vendor_bill_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finledger_vendor_entries_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/entries/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finledger_vendor_entries_reverse_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finledger/vendor/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finledger_vendor_payment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/grns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inbound_grns_list"];
        put?: never;
        post: operations["inbound_grns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/grns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inbound_grns_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/invoice-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Read an uploaded invoice into prefilled receive lines (nothing saved). */
        post: operations["inbound_invoice_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bookings still awaiting receipt, scoped to what the user may receive. */
        get: operations["inbound_pending_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_brands_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_entities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/gstins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_gstins_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_seasons_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_stores_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masters/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["masters_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/controlled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ptmapper_controlled_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ptmapper_files_list"];
        put?: never;
        post: operations["ptmapper_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ptmapper_files_retrieve"];
        put?: never;
        post?: never;
        delete: operations["ptmapper_files_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ptmapper_files_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download the mapped rows as a real .xlsx in KDPS column order. */
        get: operations["ptmapper_files_export.xlsx_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Patna pushes the reviewed file into the KDPS system: writes the append-only
         *     stock-ledger inward + (optionally) reconciles a booking, then locks the file.
         */
        post: operations["ptmapper_files_post_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Patna sends a file back to the warehouse for further edits. */
        post: operations["ptmapper_files_recall_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ptmapper_files_rerun_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Append-only correction: reverse a posted PT inward (negative mirror rows),
         *     returning the file to 'sent' so it can be fixed and re-posted.
         */
        post: operations["ptmapper_files_reverse_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/files/{id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Warehouse hand-edits the mapped KDPS rows before sending to Patna. */
        patch: operations["ptmapper_files_rows_partial_update"];
        trace?: never;
    };
    "/api/ptmapper/files/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Warehouse → Patna: hand the mapped draft over for review/posting. */
        post: operations["ptmapper_files_send_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ptmapper_review_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ptmapper/review/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Resolve one queue item → write a lookup row / taxonomy rule, then re-map
         *     every file still needing review (the resolution is remembered forever).
         */
        post: operations["ptmapper_review_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stockledger/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stockledger_entries_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stockledger/on-hand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Net stock currently on hand (Σqty > 0) grouped by SKU / brand / store.
         *
         *     Computed live from the append-only ledger: inward (+) minus reversals (−),
         *     so a fully-reversed posting simply drops out of the on-hand view.
         */
        get: operations["stockledger_on_hand_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stockledger/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stockledger_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vendors_list"];
        put?: never;
        post: operations["vendors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminRole: {
            readonly id: number;
            code: string;
            name: string;
            description?: string;
            landing_page?: string;
            nav_groups?: unknown;
            permissions_map?: unknown;
            readonly is_system: boolean;
            is_active?: boolean;
            readonly user_count: number;
        };
        AdminUser: {
            readonly id: number;
            username: string;
            full_name?: string;
            readonly role: components["schemas"]["Role"];
            role_id?: number | null;
            scope_type?: components["schemas"]["ScopeTypeEnum"];
            readonly scope_label: string;
            entity?: number | null;
            readonly entity_name: string;
            readonly stores: components["schemas"]["StoreMini"][];
            store_ids?: number[];
            is_active?: boolean;
            is_staff?: boolean;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            readonly is_superuser: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            password?: string;
        };
        Booking: {
            readonly id: number;
            number: string;
            vendor: number;
            readonly vendor_name: string;
            brand: number;
            readonly brand_name: string;
            season: number;
            readonly season_name: string;
            readonly season_code: string;
            /** @description Where the goods are expected to land (store delivery). Null = warehouse/HO. */
            destination_store?: number | null;
            readonly destination_store_name: string;
            status?: components["schemas"]["BookingStatusEnum"];
            readonly status_label: string;
            vendor_ref?: string;
            ownership?: string;
            return_terms?: string;
            /** Format: int64 */
            estimated_value_paise?: number | null;
            notes?: string;
            readonly lines: components["schemas"]["BookingLine"][];
            readonly booked_total: number;
            readonly received_total: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        BookingLine: {
            readonly id: number;
            style_code: string;
            size?: string;
            description?: string;
            booked_qty?: number;
            /** Format: int64 */
            mrp_paise?: number | null;
            received_qty?: number;
            inwarded_qty?: number;
        };
        /**
         * @description * `draft` - Draft
         *     * `booked` - Booked
         *     * `partially_received` - Partially received
         *     * `received` - Received
         *     * `closed` - Closed
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        BookingStatusEnum: "draft" | "booked" | "partially_received" | "received" | "closed" | "cancelled";
        Brand: {
            readonly id: number;
            code: string;
            name: string;
            ownership?: components["schemas"]["OwnershipEnum"];
            return_terms?: components["schemas"]["ReturnTermsEnum"];
            readonly commercial_label: string;
            is_active?: boolean;
        };
        CashLedgerEntry: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string;
            doc_number: string;
            kind: components["schemas"]["CashLedgerEntryKindEnum"];
            readonly kind_label: string;
            account?: string;
            /** Format: int64 */
            amount: number;
            readonly amount_rupees: string;
            description?: string;
            mode?: string;
            vendor?: number | null;
            /** @default  */
            readonly vendor_name: string;
        };
        /**
         * @description * `receipt` - Receipt (cash in)
         *     * `payment` - Payment (cash out)
         *     * `reversal` - Reversal
         * @enum {string}
         */
        CashLedgerEntryKindEnum: "receipt" | "payment" | "reversal";
        CustomTokenObtainPair: {
            username: string;
            password: string;
        };
        Grn: {
            readonly id: number;
            number: string;
            booking?: number | null;
            readonly booking_number: string;
            vendor?: number | null;
            readonly vendor_name: string;
            store: number;
            readonly store_code: string;
            readonly store_name: string;
            received_at?: components["schemas"]["ReceivedAtEnum"];
            status?: components["schemas"]["GrnStatusEnum"];
            readonly status_label: string;
            is_direct?: boolean;
            invoice_number?: string;
            invoice_file?: number | null;
            notes?: string;
            readonly lines: components["schemas"]["GrnLine"][];
            readonly received_total: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        GrnLine: {
            readonly id: number;
            booking_line?: number | null;
            style_code: string;
            size?: string;
            color?: string;
            barcode?: string;
            received_qty?: number;
            damaged_qty?: number;
            is_variance?: boolean;
            remark?: string;
        };
        /**
         * @description * `received` - Received
         *     * `sent_to_ho` - Sent to HO (Patna)
         *     * `inwarded` - Inwarded
         * @enum {string}
         */
        GrnStatusEnum: "received" | "sent_to_ho" | "inwarded";
        Gstin: {
            readonly id: number;
            gstin: string;
            state_code: string;
            state_name: string;
            legal_entity: number;
            readonly legal_entity_name: string;
            is_active?: boolean;
        };
        LegalEntity: {
            readonly id: number;
            code: string;
            name: string;
            pan?: string;
            is_active?: boolean;
        };
        /**
         * @description * `owned` - KDPS-owned
         *     * `brand_owned` - Brand-owned
         * @enum {string}
         */
        OwnershipEnum: "owned" | "brand_owned";
        PaginatedCashLedgerEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CashLedgerEntry"][];
        };
        PaginatedStockLedgerEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StockLedgerEntry"][];
        };
        PaginatedVendorLedgerEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["VendorLedgerEntry"][];
        };
        PatchedAdminRole: {
            readonly id?: number;
            code?: string;
            name?: string;
            description?: string;
            landing_page?: string;
            nav_groups?: unknown;
            permissions_map?: unknown;
            readonly is_system?: boolean;
            is_active?: boolean;
            readonly user_count?: number;
        };
        PatchedAdminUser: {
            readonly id?: number;
            username?: string;
            full_name?: string;
            readonly role?: components["schemas"]["Role"];
            role_id?: number | null;
            scope_type?: components["schemas"]["ScopeTypeEnum"];
            readonly scope_label?: string;
            entity?: number | null;
            readonly entity_name?: string;
            readonly stores?: components["schemas"]["StoreMini"][];
            store_ids?: number[];
            is_active?: boolean;
            is_staff?: boolean;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            readonly is_superuser?: boolean;
            /** Format: date-time */
            readonly date_joined?: string;
            password?: string;
        };
        PtFileDetail: {
            readonly id: number;
            original_filename: string;
            brand_guess?: string;
            profile_code?: string;
            profile_name?: string;
            archetype?: string;
            status?: components["schemas"]["StatusC39Enum"];
            readonly status_label: string;
            stage?: components["schemas"]["StageEnum"];
            readonly stage_label: string;
            manually_edited?: boolean;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            posted_at?: string | null;
            inward_doc_number?: string;
            booking?: number | null;
            /** @default  */
            readonly booking_number: string;
            row_count?: number;
            blank_cell_count?: number;
            unresolved_count?: number;
            error?: string;
            /** Format: date-time */
            readonly created_at: string;
            meta?: unknown;
            readonly rows: components["schemas"]["PtRow"][];
        };
        PtFileList: {
            readonly id: number;
            original_filename: string;
            brand_guess?: string;
            profile_code?: string;
            profile_name?: string;
            archetype?: string;
            status?: components["schemas"]["StatusC39Enum"];
            readonly status_label: string;
            stage?: components["schemas"]["StageEnum"];
            readonly stage_label: string;
            manually_edited?: boolean;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            posted_at?: string | null;
            inward_doc_number?: string;
            booking?: number | null;
            /** @default  */
            readonly booking_number: string;
            row_count?: number;
            blank_cell_count?: number;
            unresolved_count?: number;
            error?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        PtRow: {
            readonly id: number;
            line_no?: number;
            data?: unknown;
            blanks?: unknown;
        };
        /**
         * @description * `store` - Store
         *     * `warehouse` - Warehouse
         * @enum {string}
         */
        ReceivedAtEnum: "store" | "warehouse";
        /**
         * @description * `none` - No returns
         *     * `capped` - Capped allowance
         *     * `uncapped` - Uncapped
         *     * `rolling` - Uncapped + rolling top-up
         * @enum {string}
         */
        ReturnTermsEnum: "none" | "capped" | "uncapped" | "rolling";
        ReviewItem: {
            readonly id: number;
            dimension: string;
            raw_value: string;
            context?: unknown;
            status?: components["schemas"]["ReviewItemStatusEnum"];
            readonly status_label: string;
            resolved_value?: string;
            occurrences?: number;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `open` - Open
         *     * `resolved` - Resolved
         *     * `ignored` - Ignored
         * @enum {string}
         */
        ReviewItemStatusEnum: "open" | "resolved" | "ignored";
        Role: {
            readonly id: number;
            code: string;
            name: string;
            description?: string;
            landing_page?: string;
            nav_groups?: unknown;
            is_system?: boolean;
            is_active?: boolean;
        };
        /**
         * @description * `all` - All (network-wide)
         *     * `entity` - Legal entity
         *     * `region` - Region / state
         *     * `store_group` - Store group
         *     * `store` - Single store
         * @enum {string}
         */
        ScopeTypeEnum: "all" | "entity" | "region" | "store_group" | "store";
        Season: {
            readonly id: number;
            code: string;
            name: string;
            status?: components["schemas"]["SeasonStatusEnum"];
            sort_order?: number;
        };
        /**
         * @description * `open` - Open
         *     * `eoss` - EOSS
         *     * `closed` - Closed
         * @enum {string}
         */
        SeasonStatusEnum: "open" | "eoss" | "closed";
        /**
         * @description * `mapping` - Mapping (Warehouse)
         *     * `sent` - Sent to Patna
         *     * `posted` - Posted to system
         * @enum {string}
         */
        StageEnum: "mapping" | "sent" | "posted";
        /**
         * @description * `needs_review` - Needs review
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        StatusC39Enum: "needs_review" | "ready" | "failed";
        StockLedgerEntry: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string;
            doc_number: string;
            kind: components["schemas"]["StockLedgerEntryKindEnum"];
            readonly kind_label: string;
            readonly store_code: string;
            readonly store_name: string;
            sku_code: string;
            design?: string;
            color?: string;
            size?: string;
            brand?: string;
            season?: string;
            item?: string;
            hsn?: string;
            qty: number;
            /** Format: int64 */
            amount: number;
            readonly value_rupees: string;
            line_no?: number;
            pt_file?: number | null;
            /** @default  */
            readonly source_file: string;
            booking?: number | null;
            /** @default  */
            readonly booking_number: string;
        };
        /**
         * @description * `pt_inward` - PT inward
         *     * `pt_reversal` - PT reversal
         * @enum {string}
         */
        StockLedgerEntryKindEnum: "pt_inward" | "pt_reversal";
        Store: {
            readonly id: number;
            code: string;
            name: string;
            store_type?: components["schemas"]["StoreTypeEnum"];
            city?: string;
            gstin: number;
            readonly gstin_number: string;
            readonly state_name: string;
            readonly state_code: string;
            is_active?: boolean;
        };
        StoreMini: {
            id: number;
            code: string;
            name: string;
            store_type: string;
            state_name: string;
            state_code: string;
            gstin_number: string;
        };
        /**
         * @description * `store` - Store
         *     * `warehouse` - Warehouse
         * @enum {string}
         */
        StoreTypeEnum: "store" | "warehouse";
        Vendor: {
            readonly id: number;
            code: string;
            name: string;
            city?: string;
            gstin?: string;
            state_name?: string;
            payment_terms?: string;
            brands?: number[];
            readonly brand_names: string[];
            is_active?: boolean;
        };
        VendorLedgerEntry: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string;
            doc_number: string;
            kind: components["schemas"]["VendorLedgerEntryKindEnum"];
            readonly kind_label: string;
            vendor: number;
            readonly vendor_name: string;
            readonly vendor_code: string;
            /** Format: int64 */
            amount: number;
            readonly amount_rupees: string;
            description?: string;
            reference?: string;
            mode?: string;
            pt_file?: number | null;
            booking?: number | null;
        };
        /**
         * @description * `bill` - Bill / purchase
         *     * `payment` - Payment
         *     * `reversal` - Reversal
         * @enum {string}
         */
        VendorLedgerEntryKindEnum: "bill" | "payment" | "reversal";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_admin_meta_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_admin_roles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRole"][];
                };
            };
        };
    };
    auth_admin_roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRole"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminRole"];
                "multipart/form-data": components["schemas"]["AdminRole"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRole"];
                };
            };
        };
    };
    auth_admin_roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRole"];
                };
            };
        };
    };
    auth_admin_roles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRole"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminRole"];
                "multipart/form-data": components["schemas"]["AdminRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRole"];
                };
            };
        };
    };
    auth_admin_roles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminRole"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminRole"];
                "multipart/form-data": components["schemas"]["PatchedAdminRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRole"];
                };
            };
        };
    };
    auth_admin_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    auth_admin_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUser"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminUser"];
                "multipart/form-data": components["schemas"]["AdminUser"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUser"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminUser"];
                "multipart/form-data": components["schemas"]["AdminUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminUser"];
                "multipart/form-data": components["schemas"]["PatchedAdminUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPair"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomTokenObtainPair"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Booking"];
                "application/x-www-form-urlencoded": components["schemas"]["Booking"];
                "multipart/form-data": components["schemas"]["Booking"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    bookings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    bookings_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    files_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_cash_entries_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCashLedgerEntryList"];
                };
            };
        };
    };
    finledger_cash_entries_reverse_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_cash_movement_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_cash_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_vendor_ageing_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_vendor_balances_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_vendor_bill_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_vendor_entries_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVendorLedgerEntryList"];
                };
            };
        };
    };
    finledger_vendor_entries_reverse_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finledger_vendor_payment_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inbound_grns_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grn"][];
                };
            };
        };
    };
    inbound_grns_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Grn"];
                "application/x-www-form-urlencoded": components["schemas"]["Grn"];
                "multipart/form-data": components["schemas"]["Grn"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grn"];
                };
            };
        };
    };
    inbound_grns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grn"];
                };
            };
        };
    };
    inbound_invoice_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inbound_pending_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    masters_brands_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
        };
    };
    masters_entities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntity"][];
                };
            };
        };
    };
    masters_gstins_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gstin"][];
                };
            };
        };
    };
    masters_seasons_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Season"][];
                };
            };
        };
    };
    masters_stores_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"][];
                };
            };
        };
    };
    masters_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_controlled_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PtFileList"][];
                };
            };
        };
    };
    ptmapper_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PtFileList"];
                "application/x-www-form-urlencoded": components["schemas"]["PtFileList"];
                "multipart/form-data": components["schemas"]["PtFileList"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PtFileList"];
                };
            };
        };
    };
    ptmapper_files_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PtFileDetail"];
                };
            };
        };
    };
    ptmapper_files_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "ptmapper_files_export.xlsx_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_post_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_recall_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_rerun_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_reverse_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_rows_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_files_send_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ptmapper_review_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
        };
    };
    ptmapper_review_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stockledger_entries_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStockLedgerEntryList"];
                };
            };
        };
    };
    stockledger_on_hand_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stockledger_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    vendors_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vendor"][];
                };
            };
        };
    };
    vendors_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vendor"];
                "application/x-www-form-urlencoded": components["schemas"]["Vendor"];
                "multipart/form-data": components["schemas"]["Vendor"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vendor"];
                };
            };
        };
    };
}
