# Generated by Django 5.1.15 on 2026-07-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_saleline_cost_book_saleline_cost_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='override_at',
            field=models.DateTimeField(blank=True, help_text="The till's clock when the manager's PIN was accepted, which is not the same moment as Save & Print.", null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='override_by',
            field=models.ForeignKey(blank=True, help_text='The manager who authorised whatever on this bill needed it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_authorised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='override_kind',
            field=models.CharField(blank=True, default='', help_text='What was authorised - over_cap_discount, credit_note.', max_length=40),
        ),
    ]
